//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IN04
    {
        [Required]
        [Display(Name ="Código")]
        public string CodigoProducto { get; set; }
        [Required]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        [Required]
        public decimal Precio { get; set; }
        [Required]
        [Display(Name = "Saldo de inventario")]
        public decimal SaldoInventario { get; set; }
        [DataType(DataType.Date)]
        [Required]
        [Display(Name = "Fecha de ingreso")]
        public System.DateTime FechaIngreso { get; set; }
        [Required]
        [Display(Name = "Usuario de ingreso")]
        public string UsuarioIngreso { get; set; }
        [Required]
        [Display(Name = "Familia")]
        public int IDFamilia { get; set; }
    
        public virtual IN05 IN05 { get; set; }
    }
}
